config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
                registrations: "customer/registrations",
                sessions: "customer/sessions",
                passwords: "customers/passwords",
              }
  # # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
            registrations: "admin/registrations",
            sessions: "admin/sessions",
          }

  devise_scope :customer do
    post "customers/guest_sign_out", to: "customer/sessions#new"
    post "customers/guest_sign_in", to: "customer/sessions#new_guest"
    get "customers/guest_sign_in", to: "customer/sessions#new_guest"
    get "customers/guest_sign_up", to: "customer/sessions#new_guest"
    get "customers/guest_sign_in", to: "customer/registrations#new"
    get "customers/guest_sign_in", to: "customer/sessions#new_guest"
    delete "customer/guest_sign_out", to: "customer/sessions#destroy"
  end

  scope module: :customer do
    root to: "homes#top"

    resources :tags do
    end
    get "tag_search", to: "posts#hashtags", as: "tag_search"

    resources :customers do
      post "tag/:id" => "tags#create", as: "tag"
      delete "tag/:id" => "tags#destroy", as: "unlike"
      get "posts", to: "posts#search"
    end

    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]

      collection do
        get "search"
        get "bookmarks"
      end
    end

    resources :customers do
      member do
        get :bookmarks
      end
    end

    resources :comments, only: :destroy
    resources :bookmarks, only: :index
    post "customer/posts/:id/edit" => "customer/posts#edit"
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers
    resources :comments, only: [:index, :show, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :post
  belongs_to :customer
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  
  def index
    @comments = Comment.all.page(params[:page]).per(10)
  end

  def show
    @comment = Comment.find(params[:id])
    @customer = @comment.customer
  end

  def create
    @comment = current_customer.comments.new(comment_params)
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    @comment = comment.post
    redirect_to admin_comments_path(@comments)
  end

  private

  def comment_params
    params.require(:comment).permit(:customer_id, :post_id, :comment)
  end
end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController
  before_action :authenticate_customer!
  
  def create
    @comment = current_customer.comments.new(comment_params)
    @post = @comment.post
    if @comment.save
      redirect_to post_path(@post)
    else
      @comments = @post.comments.includes(:customer)
      render "customer/posts/show"
    end
  end
  
  def destroy
    Comment.find(params[:id]).destroy
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :comment)
  end
end

app/views/admin/comments/index.html.erb
<h1>コメント一覧</h1>
<div class="row">
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th  class="bg-light">コメント投稿日時</th>
        <th class="bg-light">コメント</th>
        <th class="bg-light">ユーザーネーム</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <% @comments.each do |comment| %>
    <tr>
      <td><%= link_to comment.updated_at.strftime("%Y/%m/%d %H:%M:%S"), admin_comment_path(comment) %></td>
      <td><%= comment.comment %></td>
      <td><%= comment.customer.name %></td>
    </tr>
    <% end %>
  </table>
</div>
<div class="text-center">
    <%= paginate @comments %>
</div>

app/views/admin/comments/show.html.erb
<h2>
  <div class="container">
    <div class="row">
      <div calss="col-xs-12">
        <span class="p-3 mb-2 bg-light text-dark">
          コメント詳細
        </span>
      </div>
    </div>
    </div>
</h2>
<p class="col-xs-5">コメント投稿日時：</p>
<div class="w-75 py-3">
  <%= @comment.created_at.strftime("%Y/%m/%d %H:%M:%S") if @comment.created_at %>
</div>
<p class="col-xs-5">コメント内容：</p>
<div class="w-100 py-3">
  <%= @comment.comment %>
</div>
<p class="col-xs-5">ユーザーネーム：</p>
<div class="w-75 py-3">
  <%= @customer.name %>
</div><br>
<div style="text-align:center">
  <div class="row actions">
    <div class="w-75 py-3">
      <%= link_to "コメント削除", admin_comment_path(@comment), method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
</div>