config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
                registrations: "customer/registrations",
                sessions: "customer/sessions",
                passwords: "customers/passwords",
              }
  # # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
            registrations: "admin/registrations",
            sessions: "admin/sessions",
          }

  devise_scope :customer do
    post "customers/guest_sign_out", to: "customer/sessions#new"
    post "customers/guest_sign_in", to: "customer/sessions#new_guest"
    get "customers/guest_sign_in", to: "customer/sessions#new_guest"
    get "customers/guest_sign_up", to: "customer/sessions#new_guest"
    get "customers/guest_sign_in", to: "customer/registrations#new"
    get "customers/guest_sign_in", to: "customer/sessions#new_guest"
    delete "customer/guest_sign_out", to: "customer/sessions#destroy"
  end

  scope module: :customer do
    root to: "homes#top"

    resources :tags do
    end
    get "tag_search", to: "posts#hashtags", as: "tag_search"

    resources :customers do
      post "tag/:id" => "tags#create", as: "tag"
      delete "tag/:id" => "tags#destroy", as: "unlike"
      get "posts", to: "posts#search"
    end

    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]

      collection do
        get "search"
        get "bookmarks"
      end
    end

    resources :customers do
      member do
        get :bookmarks
      end
    end

    resources :comments, only: :destroy
    resources :bookmarks, only: :index
    post "customer/posts/:id/edit" => "customer/posts#edit"
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers
    resources :comments, only: [:index, :show, :destroy]
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end
  
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customers = Customer.all
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      render :edit
    end
  end

  def destroy
    Customer.find(params[:id]).destroy
    redirect_to admin_customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(:id, :name, :email, :encrypted_password)
  end
end

app/controllers/customer/bookmarks_controller.rb
class Customer::BookmarksController < ApplicationController
  before_action :posts_path
  
  def index
    @bookmarks = Bookmark.where(customer: current_customer.id)
    @bookmarks = @bookmarks.page(params[:page]).per(8)
    @bookmark = Bookmark.new
    @posts = Post.all
    @post = @posts.page(params[:page])
  end
  
  def show
    @bookmark = Bookmark.find(params[:id])
    @customer = Customer.find(params[:id])
  end

  def create
    @post = Post.find(params[:post_id])
    if current_customer.nil?
      if cookies[:bookmark_post_id].nil?
        cookies.permanent[:bookmark_post_id] = @post.id.to_s
      else
        cookies.permanent[:bookmark_post_id] = cookies.permanent[:bookmark_post_id] + "," + @post.id.to_s
      end
      Bookmark.create(customer_id: nil, post_id: @post.id)
      @bookmarks_count = @post.bookmarks.count
      @cookies = cookies[:bookmark_post_id]
    else
      @bookmark = current_customer.bookmarks.new(post_id: @post.id)
      @bookmark.save
      @bookmarks_count = @post.bookmarks.count
    end
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    if current_customer.nil?
    else
      @bookmark = current_customer.bookmarks.find_by(post_id: @post.id)
      @bookmark.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def customer_params
    params.require(:bookmark).permit(:customer_id, :post_id)
  end
end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController
  before_action :authenticate_customer!
  
  def create
    @comment = current_customer.comments.new(comment_params)
    @post = @comment.post
    if @comment.save
      redirect_to post_path(@post)
    else
      @comments = @post.comments.includes(:customer)
      render "customer/posts/show"
    end
  end
  
  def destroy
    Comment.find(params[:id]).destroy
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :comment)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customer_controller.rb
class Customer::CustomerController< ApplicationController

  def index
    # @customer = Customer.new
    @posts = Post.all
    @customers = Customer.all
  end

  def show
    #   @customer = Customer.new
    # @customers = Customer.all
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end


  def new
    @customer = Customer.new
  end


#  def update
#   @customer = Customer.find(params[:id])
#    if @customer.update(customer_params)
#       redirect_to admin_customer_path
#    else
#     render :admin_customer_path
#    end

#  end

  # end


#   def update
#      @customer = Customer.find(params[:id])
#      @customer.update(customer_params)
#      redirect_to admin_customer_path(@customer)
#   end

#   def update
#   @customer = Customer.find(params[:id])
#    if @customer.update(customer_params)
#       redirect_to admin_customer_path
#    else
#     render "edit"
#    end

#   end

# def update
#         @customer = current_customer
#         if @customer.update(customer_params)
#         # flash[:update] = "You have updated user info successfully."
#         redirect_to customer_path(@customer.id)
#         else
#         render 'edit'
#         end
# end




  private
   def customer_params
    params.require(:customer).permit(:_name, :email, :encrypted_password)
   end

end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_customer, only: [:bookmarks]


  def top
    @customers = Customer.limit(4).order("id DESC")
    @customers = Customer.all
  end

  def show
    @customer = current_customer
    @customers = Customer.where(id: params[:id])
  end

  def search
    @collections = Collection.search(params[:keyword])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customers = Customer.all
    if redirect_to post_new_path(@post)
    else
      @customers = @post.customers.includes(:customer)
      render :index
    end
  end

  def update
    @customer = current_customer
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer)
    else
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    if current_customer.id == @customer.id && @customer.destroy
      redirect_to :root
    else
      redirect_to :root
    end
  end

  def destroy_confirm
    @customer = current_customer
  end

  def destroy_customer
    @customer = current_customer
    if @customer.email == 'test@test.com"'
      reset_session
      redirect_to :root
    else
      @customer.update(is_valid: false)
      reset_session
      redirect_to :root
    end
  end

  def bookmarks
    @bookmarks = Bookmark.where(customer_id: @customer.id).pluck(:post_id)
    @bookmark_posts = Post.find(bookmarks)
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :email, :encrypted_password)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  
  def top
    @posts = Post.all
    @posts = @posts.page(params[:page])
  end
  
  private
  
  def home_params
    params.require(:home).permit(:image, :address, :introduction, :hash_tags, :name)
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true
class Customer::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_customer, only: :create
  
  def ensure_normal_customer
    if params[:customer][:email].downcase == "test@test.com"
      redirect_to new_customer_session_path, alert: "ゲストユーザーのパスワード再設定はできません。"
    end
  end

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/posts_controller.rb
class Customer::PostsController < ApplicationController
  before_action :authenticate_customer!, only: [:edit, :update, :destroy]
  
  def top
    @post = Post.find(params[:id])
    if @post.save
      redirect_to post_path(@posts.id)
    else
      render :index
    end
  end
  
  def index
    @post = Post.new
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    if params[:keyword]
      @posts = @posts.search(params[:keyword]).page(params[:page])
    else
      @posts = @posts.page(params[:page])
    end
  end
  
  def show
    @bookmark_count = Bookmark.where(post_id: params[:id]).count
    @post = Post.find(params[:id])
    @comments = @post.comments
    @posts = @post.post_tags.page(params[:page])
    @comment = Comment.new
  end
  
  def new
    @post = Post.new
    @post = current_customer.posts.build
  end

  def create
    @post = current_customer.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @post.customer.name
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
  def find_post
    @post = Post.find(params[:id])
  end

  def force_redirect_unless_my_post
    return redirect_to root_path, alert: "権限がありません" if @post.customer != current_customer
  end

  def bookmarks
    @posts = current_customer.posts
    @posts = current_customer.bookmarks_posts
  end

  def search
    @posts = Post.all
    @tags = Tag.all
    @customers = Customer.search(params[:keyword])
    if params[:keyword].present?
      @keyword = params[:keyword]
    else
      @posts = Post.all
    end
    @tag_list = Tag.all
    @customers = Customer.all
    if params[:name].present?
      @customerrs = Customer.where("post LIKE ?", "%#{params[:post]}%")
    else
      @customers = Customer.none
    end
  end

  def hashtags
    if params[:hashtags].present?
      tag_name = params[:hashtags].downcase
      tag = Tag.find_by(tag_name: tag_name)
      if tag.nil?
        @posts = Kaminari.paginate_array([]).page(params[:page]).per(8)
      else
        @posts = tag.posts.page(params[:page]).per(8)
      end
    else
      @posts = Post.all.page(params[:page]).per(8)
    end
  end
  
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post  was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def ensure
    @post = current_customer.posts
    @post = @posts.find_by(id: params[:id])
    redirect_to new_post_path unless @post
  end

  private

  def post_params
    params.require(:post).permit(:image, :address, :introduction, :hash_tags, :name)
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true
class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_in_params, only: [:update]
 
  # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource_or_scope)
    root_path(resource)
  end

  # def after_sign_up_path_for(resource_or_scope)
  # "/customer/#{current_customer.id}"
  # end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   #super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/searches_controller.rb
class Customer::SearchesController < ApplicationController
  def index
  end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController

  # def guest_sign_in
  #   user = User.guest
  #   sign_in user
  #   redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  # end

  # before_action :configure_sign_in_params, only: [:create]

  # ログイン後のリダイレクト先
  # def after_sign_in_path_for(resource_or_scope)
  #   root_path(resource)
  # end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def new_guest
    customer = Customer.guest
    sign_in customer
    redirect_to root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in

  def create
    p "-------create-----"
    p params
    p configure_sign_in_params
    p "------------"
    super
  end

  # def create
  #   p "==================="
  #   p params
  #   p "==================="
  #   customer = Customer.find_by(email: params[:session][:email])
  #   if customer && customer.authenticate(params[:session][:password])
  #     session[:customer_id] = customer.id
  #     redirect_to root_path
  #   else
  #     render :new
  #   end
  # end

  # DELETE /resource/sign_out
  # def destroy
  # remember_me
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
  end
end

app/controllers/customer/tags_controller.rb
class Customer::TagsController < ApplicationController
  
  def top
    @tags = Tag.all
  end

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @posts = Post.all
  end

  def destroy
    Tag.find(params[:id]).destroy()
    redirect_to tags_path
  end
  
  private

  def tags_params
    params.require(:tag).permit(:id, :tag_name)
  end
end

app/helpers/customers/bookmarks_helper.rb
module Customers::BookmarksHelper
end

app/helpers/customers/searches_helper.rb
module Customers::SearchesHelper
end

app/views/customer/posts/_form.html.erb
<small>スペースで区切ることで複数指定できます。</small><br>
<%= link_to image_tag(@post.image.variant(resize: "100x100")), post_path(@post.id) %>
<%= link_to @post.customer.name, customer_path(@post.customer.id) %>
<i class="fa fa-heart unlike-btn"></i>
<%= @post.bookmarks.length %>
<%= link_to @post.introduction, post_path(@post.id) %>
<i class="fa fa-heart unlike-btn"></i>

app/views/customer/posts/edit.html.erb
<h2>
  <div class="container">
    <span class="p-3 mb-2 bg-light text-dark">投稿編集</span>
  </div>
</h2><br>
<div class="mx-auto" style="width: 400px">
  <%= form_with(model: @post, url: post_path, local: true, method: :put) do |f| %>
  <div class="row inputImage">
    <div class="w-25 py-2"><%= f.label :写真 %></div>
    <div><%= f.file_field :image, placeholder: "写真", accept: "image/*" %></div>
  </div>
  <div class="row field">
    <div class="w-25 py-2"><%= f.label :写真の住所 %></div>
    <div><%= f.text_field :address, autofocus: true, id: "inputName", placeholder: "〒997-0045  山形県鶴岡市西新斎町9-10" %></div>
  </div>
  <div class="row field">
    <div class="w-25 py-2"><%= f.label :写真の紹介文 %></div>
    <div><%= f.text_area :introduction, placeholder: "ここに紹介文を記述します。", size: "30x5" %></div>
    </div>
    <div class="row field">
      <div class="w-25 py-2"><%= f.label :タグ %></div>
      <div><%= f.text_field :hash_tags, autofocus: true, id: "inputPrice", placeholder: "＃山形県 ＃水族館 ＃クラゲ" %></div>
    </div>
    <div style="text-align:center">
      <div class="row actions">
        <div class="w-75 py-3">
          <%= f.submit "編集内容を保存する", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/customer/posts/hashtags.html.erb
<div class="mx-auto" style="width: 1000px">
	<div class="container">
		<span class="p-3 mb-2 bg-light text-dark">おすすめの撮影スポット一覧</span>
	</div>
</div>
<div class="container mt-5">
	<div class="row justify-content-center">
		<div class="col-12">
			<div class="text-left">
				<table class="col-lg table-bordered">
					<thead class="bg-light">
						<tr>
							<td class="text-left">写真</td>
							<td class="text-left">投稿日</td>
							<td class="text-left">写真の住所</td>
							<td class="text-left">写真の紹介文</td>
							<td class="text-left">タグ</td>
							<td class="text-left">投稿者</td>
							<td class="text-left">詳細</td>
						</tr>
					</thead>
				<tbody>
					<tr>
						<% @posts.each do |post| %>
						<th>
							<% if post.image.attached? %>
							<%= image_tag post.image, size: "45x45" %>
							<% else %>
							</th>
							<th><%= image_tag "no_image", size: "45x45" %>
							<% end %>
							</th>
							<td><%= post.created_at.strftime("%Y/%m/%d") %></td>
							<td><%= post.address %><br></td>
							<td><%= post.introduction %></td>
							<td><%= post.hash_tags %><br></td>
							<td><%= post.customer.name %></td>
							<%= form_with model: @post, url: posts_url, method: :post do |f| %>
							<td><%= link_to "表示する", post_path(post), class: "btn btn-primary" %></td>
							<% end %>
					</tr>
				</tbody>
			<% end %>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="text-center">
	<p><%= paginate @posts %></p>
</div>

app/views/customer/posts/index.html.erb
<div class="mx-auto" style="width: 1000px">
	<div class="container">
		<span class="p-3 mb-2 bg-light text-dark">おすすめの撮影スポット一覧</span>
	</div>
</div>
<div class="d-flex justify-content-end">
  <%= form_with url: posts_path, method: :get, local: true, class: "boards__searchForm" do |f| %>
  <div class="input-group">
    <%= f.text_field :keyword, value: @keyword, class: "form-control search-control", placeholder: "キーワードを入力" %>
    <span class="input-group-btn input-group-append">
      <%= button_tag name: "", class: "btn btn-secondary" do %>
      <i class="fas fa-search"></i>検索
      <% end %>
    </span>
  </div>
</div>
<% end %><br>
<div class="container mt-5">
	<div class="row justify-content-center">
		<div class="col-12">
			<div class="text-left">
				<table class="col-lg table-bordered">
					<thead class="bg-light">
						<tr>
							<td class="text-left">写真</td>
							<td class="text-left">投稿日</td>
							<td class="text-left">写真の住所</td>
							<td class="text-left">写真の紹介文</td>
							<td class="text-left">タグ</td>
							<td class="text-left">投稿者</td>
							<td class="text-left">詳細</td>
						</tr>
					</thead>
					<tbody>
						<tr><% @posts.each do |post| %>
						<th>
							<% if post.image.attached? %>
							<%= image_tag post.image, size: "45x45" %>
							<% else %>
						</th>
						<th><%= image_tag "no_image", size: "45x45" %>
						<% end %>
						</th>
						<td><%= post.created_at.strftime("%Y/%m/%d") %></td>
						<td><%= post.address %><br></td>
						<td><%= post.introduction %></td>
						<td><%= post.hash_tags %><br></td>
						<td><%= post.customer.name %></td>
						<%= form_with model: @post, url: posts_url, method: :post do |f| %>
						<td><%= link_to "表示する", post_path(post), class: "btn btn-primary" %></td>
						<% end %>
						</tr>
					<% end %>
				  </tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="text-center">
	<p><%= paginate @posts %></p>
</div>

app/views/customer/posts/new.html.erb
<h2>
  <div class="container">
    <span class="p-3 mb-2 bg-light text-dark">新規投稿📷</span>
    <h4>※全ての項目を入力して投稿して下さい！
  </div>
</h2>
<div class="mx-auto" style="width: 650px">
  <p><% if @post.errors.any? %>
  <div class="alert-danger">
    <h3><%= @post.errors.count %>件のエラーが発生しました。</h3>
    <p><% @post.errors.full_messages.each do |message| %></p>
    <p class='error-message'><%= message %></p>
    <% end %>
  </div>
<% end %>
  </p>
</div><br>
<div class="mx-auto" style="width: 400px">
  <%= form_with model: @post, url: posts_path do |f| %>
  <div class="row inputImage">
    <div class="w-25 py-2"><%= f.label :写真 %></div>
    <div><%= f.file_field :image, placeholder: "写真", accept: "image/*" %></div>
  </div>
  <div class="row field">
    <div class="w-25 py-2"><%= f.label :写真の住所 %></div>
    <div><%= f.text_field :address, autofocus: true, id: "inputName", placeholder: "〒997-0045  山形県鶴岡市西新斎町9-10" %></div>
  </div>
  <div class="row field">
    <div class="w-25 py-2"><%= f.label :写真の紹介文 %></div>
    <div><%= f.text_area :introduction, placeholder: "ここに紹介文を記述します。", size: "30x5" %></div>
  </div>
  <div class="row field">
    <div class="w-25 py-2"><%= f.label :タグ %></div>
    <div><%= f.text_field :hash_tags, autofocus: true, id: "inputPrice", placeholder: "＃山形県 ＃水族館 ＃クラゲ" %></div>
  </div>
  <div style="text-align:center">
    <div class="row actions">
      <div class="w-75 py-3"><%= f.submit "投稿する", class: "btn btn-success" %></div>
  </div>
</div>
<% end %>
</div>

app/views/customer/posts/search.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="d-flex justify-content-end">
      <%= form_with url: posts_path, method: :get, local: true, class: "boards__searchForm" do |f| %>
      <div class="input-group">
        <%= f.text_field :keyword, value: @keyword, class: "form-control search-control", placeholder: "キーワードを入力" %>
        <span class="input-group-btn input-group-append">
          <%= button_tag name: "", class: "btn btn-secondary" do %>
          <i class="fas fa-search"></i>検索
          <% end %>
        </span>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/customer/posts/show.html.erb
<div class="row">
  <div class="col-md-12">
    <% if @post.image.attached? %>
    <%= image_tag @post.image, class: "img-fluid" %>
    <% else %>
    <%= image_tag "no_image", class: "img_fluid" %>
    <% end %>
  </div>
  <div class="col-md-6">
    <p>写真の住所：<%= @post.address %></p>
    <p>写真の紹介文：<%= @post.introduction %></p>
    <p>タグ：<%= @post.hash_tags %></p>
    <p>投稿日時：<%= @post.created_at.strftime("%Y/%m/%d") %></p>
    <p>投稿者：<%= @post.customer.name %></p>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <% if customer_signed_in? %>
    <div class="like-btn">
      <% if current_customer && current_customer.bookmark?(@post.id) %>
      <%= link_to post_bookmarks_path(@post), method: :delete, remote: false do %>
      <span class="fa fa-heart like-btn-unlike"></span>
      <% end %>
      <% else %>
      <%= link_to post_bookmarks_path(@post), method: :post, remote: false do %>
      <span class="fa fa-heart-o like-btn"></span>
      <% end %>
      <% end %>
    </div>
    <% end %>
    <div class="like-btn">
      <h3>いいね件数：<%= @bookmark_count %></h3>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <% if customer_signed_in? %>
    <%= form_with model: [@post, @comment] do |f| %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <div class="form-group">
      <%= f.text_area :comment, rows: "5", placeholder: "コメントをここに入力する。", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "送信する", class: "btn btn-success btn-block" %>
    </div>
    <% end %>
  </div>
  <% end %>
</div>
<div class="col-md-8">
  <h3>コメント件数：<%= @post.comments.count %></h3>
  <% @comments.each do |comment| %>
  <table class="table">
    <tbody>
      <tr>
        <td>ユーザーネーム：</td>
        <td><%= comment.customer.name %></td>
        <td>コメント投稿日時：</td>
        <td><%= comment.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
        <% if comment.customer == current_customer %>
        <%= link_to "消去", comment_path(comment), method: :delete, remote: false, class: "btn btn-xs btn-danger" %>
        <% end %>
        </td>
      </tr>
      <tr>
        <td>コメント内容:</td>
        <td><%= comment.comment %></td>
      </tr>
    </tbody>
  </table>
  <% end %>
</div>
<div class="actions  col-xs-6 col-xs-offset-4">
  <% if customer_signed_in? && current_customer.id == @post.customer_id %>
  <div class="text-center">
    <%= link_to "編集する", edit_post_path(@post.id), class: "btn btn-primary" %>
    <%= link_to "削除する", post_path, method: :delete, class: "btn btn-danger" %>
  </div>
</div>
  <% end %>